# How to Python?

##  A little bit of context 


If you came here, it is certainly because you want to learn a little bit about programming, and more precisely about programming with python. This tutorial aims at teaching you the very basics of programming using python and will give you a few examples to start working with. If you have any demands, or any remarks to improve this tutorial, please do not hesitate to adress them at vincent.borne@protonmail.com.

### Programming? Python?


Programming is the action of giving intructions to a machine, hoping in return for this machine to effectuate a certain number of processes and give you back a result. The very first computer programm is known to have been written in 1843 by Ada Lovelace to calculate sequence of Bernoulli numbers on Charles Babbage's Analytical Engine.
   

Of course to be able to give instructions to a computer, you need to speak the same language. Which means that either you are fluent in binary (the succession of 0 and 1 with which your computer works) or you use a programming language such as python which will translate and talk to the computer for you. There are many other programming languages such as C, C++, Octave, Java etc... each one with their specificities, advantages and flaws.

Python is depicted as "an easy to learn, powerful programming language. It has efficient high-level data structures and a simple but effective approach to object-oriented programming. Python's elegant syntax and dynamic typing, together with its interpreted nature, make it an ideal language for scripting and rapid application development in many areas on most platforms.". Its simplicity and the large choice of librairies and tools that does the work for you for most of the simple actions that you might require, makes it a efficient and reliable tool, for beginners but also for a lot of advanced projects. 

In case you wonder the name "Python" comes from the love of its creator, Guido van Rossum, for the english BBC show "Monty Python's Flying Circus". 

##  Where do I programm? 

When you are programming you need two different tool: 
1) the interpreter prompt or console, in which you execute your code. You can also enter directly commands in the prompt , in general short ones. You can type for example, 

In [4]:
print("Hello world!")

Hello world!


Here you just entered a single statement and python returned the result of this statement : the sentence "Hello world!".

But if you need to build slightly more complex statements, you will want to use an editor to do so, i.e an environment in which you can easily build a complex command, before running it using the prompt. 
You have a large choice of them, but I would recommand in a first time to use editors attached to a Python prompt like spyder (available when downloading anaconda) pyzo, or  [Pycharm](https://www.jetbrains.com/education/download/#section=pycharm-edu). If you are more used to programming you might want to try [Atom](https://atom.io/), [Vim](https://www.vim.org/) or [Emacs](http://www.gnu.org/software/emacs/). And now you are ready to start! 

##   How does it works?


###  Litteral constant and variables

To start wrinting a new code you can place yourself in your favorite editor. This is where you will design the statements that you want to make, before executing them.

In [6]:
985*654+78/(89-6) #I can comment a line of code by adding # afterwards. 
#This will be ignored by the console. 

644190.9397590362

I can also give name and values to some variables to play around. These variable are stored in your computer memory and to access them you need to call them by their name :


In [14]:
from math import * #I am importing a library that defines pi for me
eps0=8.854*10**(-12)
q1=-1
q2=2
r1carré=6 #I have stored all the previous values 
#and now I can call them to execute my calculus
F12=(1/(4*pi*eps0))*(q1*q2/r1carré)
print('F12=',F12) #here I use the function print (already defined in python) 
#to return two different object: a string and a number

F12= -2995914145.996073


In the previous code you can notice the line "from math import ". Those lines at the beginnig of your code allows you to call modules, i.e other pieces of code made by other people or yourself that defines a lot of objects for you. Here the module math defines for the variable "pi" for me. The star means that I wanted all of the library to be imported but I could have also used "from math import pi" to save some computationnal time since this is the only variable that I am using.

In the first times you will mainly use litteral constants, i.e strings or numbers that have a litteral value and are constant. Strings are sequences of characters that you express in quotes ("" or ''). For the numbers you can distinguish the *integers* numbers (for example 5 is a whole number) and *floating point* numbers (for example 5.12 or pi). Those are different type of objects :


In [1]:
string= 'I am a string '
integer= 3
floating=3.58
print('String type is',type(string))
print('integer type is',type(integer))
print('floating number type is',type(floating))

String type is <class 'str'>
integer type is <class 'int'>
floating number type is <class 'float'>


If you want to know a little bit more about the different type of objects and learn how to play around with strings you can find more informations [here](https://python.swaroopch.com/basics.html). 

###  Loops 

One of the big advantages of computer programms is that they can effectuate really quickly some repetitive tasks, that would otherwise take us a long time to perform (and also would be really annoying). To do so we use loops, that will run a certain programm again and again until a certain goal is reached. In Python, the indentation defines the limits of the beginning and the end of the loop. Spaces do not count. When something is wrong in your loop there is a high chance that you made a indentation mistakes somewhere! You can find a few examples of loops below :



- The IF loop 

In [4]:
Boolvar =  str(input('Enter True or False : '))
if Boolvar == 'True' :#here start my loop based on a condition 
    #that my variable must fullfill
    print('Nice this is true') # I indented the result 
    #that should be printed if my condition is met
elif Boolvar == 'False':
    print("Well this is false")
else:
    print('you did not entered a the wanted answer')

print('Done')
# This last statement is always executed,
# after the if statement is executed.

Enter True or False : False
Well this is false
Done


- The WHILE loop


In [13]:
number = 23
running = True

while running:
    guess = int(input('Enter an integer : '))

    if guess == number:
        print('Congratulations, you guessed it.')
        # this causes the while loop to stop
        running = False
    elif guess < number:
        print('No, it is a little higher than that.')
    else:
        print('No, it is a little lower than that.')
else:
    print('The while loop is over.')
    # Do anything else you want to do here

print('Done')


Enter an integer : 25
No, it is a little lower than that.
Enter an integer : 20
No, it is a little higher than that.
Enter an integer : 23
Congratulations, you guessed it.
The while loop is over.
Done


- The FOR loop 

In [17]:
from math import factorial
for i in range (1, 10): # is taking values from 1 to 9 
    x=factorial(i)
    print(x)
print('Done')

1
2
6
24
120
720
5040
40320
362880
Done


- BREAK and CONTINUE loops

This two statement are a bit specific since they are made to interrupt the "normal" behavior of the loop. The break statement is used to break out of a loop statement i.e. stop the execution of a looping statement, even if the loop condition has not become False or the sequence of items has not been completely iterated over. The continue statement is used to tell Python to skip the rest of the statements in the current loop block and to continue to the next iteration of the loop. The next examples have been taken from this [tutorial](https://python.swaroopch.com/control_flow.html) that I once recommand for more detailed informations.

In [3]:
while True:
    s = input('Enter something : ')
    if s == 'quit':
        break
    print('Length of the string is', len(s))
print('Done')


Enter something : skipadabadadada
Length of the string is 15
Enter something : noice
Length of the string is 5
Enter something : one last for the road
Length of the string is 21
Enter something : quit
Done


In [2]:
while True:
    s = input('Enter something : ')
    if s == 'quit':
        break
    if len(s) < 3:
        print('Too small')
        continue
    print('Input is of sufficient length')

Enter something : no
Too small
Enter something : come on
Input is of sufficient length
Enter something : thanks!
Input is of sufficient length
Enter something : quit


###  Functions 

Another really usefull tool that one can use with python are functions. Like for mathematical functions those are littles pieces of code inside your code that you feed with variables and that will return some wanted results. It is particularly interesting to simplify and clear the code whenever you are using multiples or complex functions at the same time. 

In [6]:
from math import pi
eps0=8.854*10**(-12)
q1=-1
q2=2
r1=6

def F12(eps,q1,q2,r): #this is where we define a function of 
    #different parameters (q, r, epsilon)
    F12=(1/(4*pi*eps))*(q1*q2/r**2)
    return F12

ans = F12(eps0,q1,q2,r1)
print(ans)

-499319024.3326788


In [7]:
import numpy as np
nx, ny = 4, 4
def E(q, r0, x, y): # a more complex example
    """Return the electric field vector E=(Ex,Ey) due to charge q at r0."""
    den = np.sqrt((x-r0[0])**2 + (y-r0[1])**2)**3
    Ex = q * (x - r0[0]) / den
    Ey = q * (y - r0[1]) / den
    return Ex, Ey #this is what the function returns afterwards
x = np.linspace(-2, 2, nx)
y = np.linspace(-2, 2, ny)
X, Y = np.meshgrid(x, y)
charge_positions = [[0,1]]
charges          = [1]
ex,ey = E(charges[0],charge_positions[0],X,Y)
print(ex)
print(ey)

[[-0.04266925 -0.02296911  0.02296911  0.04266925]
 [-0.11334412 -0.11525918  0.11525918  0.11334412]
 [-0.23993366 -1.60996894  1.60996894  0.23993366]
 [-0.17888544 -0.38402321  0.38402321  0.17888544]]
[[-0.06400387 -0.10336098 -0.10336098 -0.06400387]
 [-0.09445344 -0.28814794 -0.28814794 -0.09445344]
 [-0.03998894 -0.80498447 -0.80498447 -0.03998894]
 [ 0.08944272  0.57603482  0.57603482  0.08944272]]


Once again if you wish to go further go [here](https://python.swaroopch.com/functions.html).

###  lists

A list is an object that contains a certain numbers of items, like a shopping list or a matrix. You can create them easily:


In [8]:
list1=['tomatoes','salt','zucchinis','tofu','pastas','toilet paper']
print(list1)
list2= [[1, 4, 5], [-5, 8, 9]] #a list of list (a matrix)
print(list2)

['tomatoes', 'salt', 'zucchinis', 'tofu', 'pastas', 'toilet paper']
[[1, 4, 5], [-5, 8, 9]]


You can then navigate inside those lists:


In [9]:
list1=['leeks','salt','zucchinis','tofu','pastas','toilet paper']
list2= [[1, 4, 5], [-5, 8, 9]]
print(list1[0])
print(list1[3])
print(list1[-1])
print(list2[1])
print(list2[0][2])


leeks
tofu
toilet paper
[-5, 8, 9]
5


You will notice that the numbering of the list starts at zero and that you can go throught the list items backwards by using negatives. 

This is it for the moment, we might go over some more complex stuff in the coming weeks, and I might modify it in a near future depending of the feedback that I receive. If you want to improve or add stuff to the present work please feel free to do so.

In [10]:
print('that s all folks!')

that s all folks!
